import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export interface Language {
  name: string;
  code: string;
  flag: string;
}

export const languages: Language[] = [
  { "name": "Deutsch", "code": "de", "flag": "🇩🇪" },
  { "name": "English", "code": "en", "flag": "🇬🇧" },
  { "name": "Türkçe", "code": "tr", "flag": "🇹🇷" },
  { "name": "Русский", "code": "ru", "flag": "🇷🇺" },
  { "name": "Polski", "code": "pl", "flag": "🇵🇱" },
  { "name": "العربية", "code": "ar", "flag": "🇸🇦" },
  { "name": "Kurdî", "code": "ku", "flag": "🏳️" },
  { "name": "Italiano", "code": "it", "flag": "🇮🇹" },
  { "name": "Bosanski", "code": "bs", "flag": "🇧🇦" },
  { "name": "Hrvatski", "code": "hr", "flag": "🇭🇷" },
  { "name": "Srpski", "code": "sr", "flag": "🇷🇸" },
  { "name": "Română", "code": "ro", "flag": "🇷🇴" },
  { "name": "Ελληνικά", "code": "el", "flag": "🇬🇷" },
  { "name": "Español", "code": "es", "flag": "🇪🇸" },
  { "name": "Français", "code": "fr", "flag": "🇫🇷" },
  { "name": "हिन्दी", "code": "hi", "flag": "🇮🇳" },
  { "name": "اردو", "code": "ur", "flag": "🇵🇰" },
  { "name": "Tiếng Việt", "code": "vi", "flag": "🇻🇳" },
  { "name": "中文", "code": "zh", "flag": "🇨🇳" },
  { "name": "فارسی", "code": "fa", "flag": "🇮🇷" },
  { "name": "پښتو", "code": "ps", "flag": "🇦🇫" },
  { "name": "தமிழ்", "code": "ta", "flag": "🇱🇰" },
  { "name": "Shqip", "code": "sq", "flag": "🇦🇱" },
  { "name": "Dansk", "code": "da", "flag": "🇩🇰" },
  { "name": "Українська", "code": "uk", "flag": "🇺🇦" }
];

interface LanguageContextType {
  currentLanguage: string;
  setLanguage: (code: string) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

interface LanguageProviderProps {
  children: ReactNode;
}

const detectLanguageFromBrowser = (): string => {
  const browserLang = navigator.language.split('-')[0];
  const supportedCodes = languages.map(lang => lang.code);
  return supportedCodes.includes(browserLang) ? browserLang : 'de';
};

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [currentLanguage, setCurrentLanguage] = useState<string>('de');

  useEffect(() => {
    const savedLanguage = localStorage.getItem('selectedLanguage');
    if (savedLanguage && languages.some(lang => lang.code === savedLanguage)) {
      setCurrentLanguage(savedLanguage);
    } else {
      const detectedLanguage = detectLanguageFromBrowser();
      setCurrentLanguage(detectedLanguage);
    }
  }, []);

  const setLanguage = (code: string) => {
    setCurrentLanguage(code);
    localStorage.setItem('selectedLanguage', code);
  };

  const t = (key: string): string => {
    return translations[currentLanguage]?.[key] || translations['de'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ currentLanguage, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

const translations: Record<string, Record<string, string>> = {
  de: {
    title: "Müll-Sortierhilfe",
    subtitle: "Richtige Mülltrennung in Deutschland",
    description: "Geben Sie Ihre Postleitzahl ein und laden Sie ein Foto Ihres Mülls hoch. Wir helfen Ihnen dabei, ihn richtig zu sortieren.",
    postalCodeLabel: "📍 Postleitzahl",
    postalCodePlaceholder: "10115",
    uploadPhotoLabel: "📸 Foto hochladen",
    uploadPhoto: "Foto hochladen",
    uploadPhotoDescription: "Klicken Sie hier oder ziehen Sie ein Foto Ihres Mülls hierher",
    analyzeButton: "🔍 Meinen Müll analysieren",
    analyzing: "Analysiere...",
    validPostalCode: "Gültige Postleitzahl",
    invalidPostalCode: "⚠️ Bitte geben Sie eine gültige 5-stellige deutsche Postleitzahl ein",
    whyImportant: "Warum ist richtige Mülltrennung wichtig?",
    reason1: "Umweltschutz durch Recycling und Wiederverwertung",
    reason2: "Reduzierung der Deponiemenge und CO2-Emissionen",
    reason3: "Einhaltung der deutschen Umweltgesetze",
    reason4: "Kosteneinsparungen bei der Müllentsorgung",
    languageSelector: "Sprache wählen",
    analysisComplete: "Analyse abgeschlossen",
    analysisCompleteDescription: "Hier sind Ihre Sortieranweisungen",
    analysisError: "Analyse fehlgeschlagen",
    analysisErrorDescription: "Es ist ein Fehler aufgetreten",
    newAnalysis: "Neue Analyse starten",
    genericError: "Ein unerwarteter Fehler ist aufgetreten. Bitte versuchen Sie es erneut.",
    // Location detection
    detectLocation: "Standort ermitteln",
    geolocationNotSupported: "Geolokalisierung wird von diesem Browser nicht unterstützt",
    locationPermissionDenied: "Zugriff auf Standort wurde verweigert",
    locationUnavailable: "Standort ist nicht verfügbar",
    locationTimeout: "Zeitüberschreitung bei Standortermittlung",
    locationError: "Fehler bei der Standortermittlung",
    geocodingError: "Fehler beim Ermitteln der Postleitzahl",
    noGermanPostalCodeFound: "Keine deutsche Postleitzahl für diesen Standort gefunden",
    apiKeyRestrictionError: "API-Schlüssel-Beschränkungsfehler. Bitte kontaktieren Sie den Administrator."
  },
  en: {
    title: "Waste Sorting Helper",
    subtitle: "Proper Waste Separation in Germany",
    description: "Enter your postal code and upload a photo of your waste. We'll help you sort it correctly.",
    postalCodeLabel: "📍 Postal Code",
    postalCodePlaceholder: "10115",
    uploadPhotoLabel: "📸 Upload Photo",
    uploadPhoto: "Upload Photo",
    uploadPhotoDescription: "Click here or drag a photo of your waste here",
    analyzeButton: "🔍 Analyze My Waste",
    analyzing: "Analyzing...",
    validPostalCode: "Valid postal code",
    invalidPostalCode: "⚠️ Please enter a valid 5-digit German postal code",
    whyImportant: "Why is proper waste sorting important?",
    reason1: "Environmental protection through recycling and reuse",
    reason2: "Reduction of landfill waste and CO2 emissions",
    reason3: "Compliance with German environmental laws",
    reason4: "Cost savings in waste disposal",
    languageSelector: "Select Language",
    analysisComplete: "Analysis Complete",
    analysisCompleteDescription: "Here are your sorting instructions",
    analysisError: "Analysis Failed",
    analysisErrorDescription: "An error occurred during analysis",
    newAnalysis: "Start New Analysis",
    genericError: "An unexpected error occurred. Please try again.",
    // Location detection
    detectLocation: "Detect Location",
    geolocationNotSupported: "Geolocation is not supported by this browser",
    locationPermissionDenied: "Location access was denied",
    locationUnavailable: "Location is unavailable",
    locationTimeout: "Location detection timeout",
    locationError: "Error detecting location",
    geocodingError: "Error determining postal code",
    noGermanPostalCodeFound: "No German postal code found for this location",
    apiKeyRestrictionError: "API key restriction error. Please contact administrator."
  },
  ru: {
    title: "Помощник по сортировке мусора",
    subtitle: "Правильная сортировка отходов в Германии",
    description: "Введите ваш почтовый индекс и загрузите фото вашего мусора. Мы поможем правильно его отсортировать.",
    postalCodeLabel: "📍 Почтовый индекс",
    postalCodePlaceholder: "10115",
    uploadPhotoLabel: "📸 Загрузить фото",
    uploadPhoto: "Загрузить фото",
    uploadPhotoDescription: "Нажмите здесь или перетащите фото вашего мусора сюда",
    analyzeButton: "🔍 Анализировать мой мусор",
    analyzing: "Анализируем...",
    validPostalCode: "Действительный почтовый индекс",
    invalidPostalCode: "⚠️ Пожалуйста, введите действительный 5-значный немецкий почтовый индекс",
    whyImportant: "Почему важна правильная сортировка мусора?",
    reason1: "Защита окружающей среды через переработку и повторное использование",
    reason2: "Сокращение количества свалок и выбросов CO2",
    reason3: "Соблюдение немецкого экологического законодательства",
    reason4: "Экономия средств на утилизации отходов",
    languageSelector: "Выбрать язык",
    analysisComplete: "Анализ завершен",
    analysisCompleteDescription: "Вот ваши инструкции по сортировке",
    analysisError: "Ошибка анализа",
    analysisErrorDescription: "Произошла ошибка во время анализа",
    newAnalysis: "Начать новый анализ",
    genericError: "Произошла неожиданная ошибка. Пожалуйста, попробуйте снова.",
    // Location detection
    detectLocation: "Определить местоположение",
    geolocationNotSupported: "Геолокация не поддерживается этим браузером",
    locationPermissionDenied: "Доступ к местоположению был запрещен",
    locationUnavailable: "Местоположение недоступно",
    locationTimeout: "Тайм-аут определения местоположения",
    locationError: "Ошибка определения местоположения",
    geocodingError: "Ошибка определения почтового индекса",
    noGermanPostalCodeFound: "Немецкий почтовый индекс для этого местоположения не найден",
    apiKeyRestrictionError: "Ошибка ограничения API ключа. Обратитесь к администратору."
  },
  // ... (остальные языки с добавленными переводами для новых ключей)
  tr: {
    title: "Atık Ayırma Yardımcısı",
    subtitle: "Almanya'da Doğru Atık Ayrımı",
    description: "Posta kodunuzu girin ve atığınızın fotoğrafını yükleyin. Doğru şekilde ayırmanıza yardımcı olalım.",
    postalCodeLabel: "📍 Posta Kodu",
    postalCodePlaceholder: "10115",
    uploadPhotoLabel: "📸 Fotoğraf Yükle",
    uploadPhoto: "Fotoğraf Yükle",
    uploadPhotoDescription: "Buraya tıklayın veya atığınızın fotoğrafını buraya sürükleyin",
    analyzeButton: "🔍 Atığımı Analiz Et",
    analyzing: "Analiz ediliyor...",
    validPostalCode: "Geçerli posta kodu",
    invalidPostalCode: "⚠️ Lütfen geçerli 5 haneli Alman posta kodu girin",
    whyImportant: "Doğru atık ayırma neden önemli?",
    reason1: "Geri dönüşüm ve yeniden kullanım yoluyla çevre koruma",
    reason2: "Depolama alanı atığının ve CO2 emisyonlarının azaltılması",
    reason3: "Alman çevre yasalarına uyum",
    reason4: "Atık bertarafında maliyet tasarrufu",
    languageSelector: "Dil Seç",
    analysisComplete: "Analiz Tamamlandı",
    analysisCompleteDescription: "İşte ayırma talimatlarınız",
    analysisError: "Analiz Başarısız",
    analysisErrorDescription: "Analiz sırasında bir hata oluştu",
    newAnalysis: "Yeni Analiz Başlat",
    genericError: "Beklenmeyen bir hata oluştu. Lütfen tekrar deneyin.",
    detectLocation: "Konumu Tespit Et",
    geolocationNotSupported: "Coğrafi konum bu tarayıcı tarafından desteklenmiyor",
    locationPermissionDenied: "Konum erişimi reddedildi",
    locationUnavailable: "Konum mevcut değil",
    locationTimeout: "Konum tespiti zaman aşımı",
    locationError: "Konum tespit hatası",
    geocodingError: "Posta kodu belirleme hatası",
    noGermanPostalCodeFound: "Bu konum için Alman posta kodu bulunamadı",
    apiKeyRestrictionError: "API anahtarı kısıtlama hatası. Lütfen yöneticiyle iletişime geçin."
  },
  pl: {
    title: "Asystent Sortowania Odpadów",
    subtitle: "Prawidłowa segregacja odpadów w Niemczech",
    description: "Wprowadź swój kod pocztowy i prześlij zdjęcie swoich odpadów. Pomożemy Ci je prawidłowo posortować.",
    postalCodeLabel: "📍 Kod pocztowy",
    postalCodePlaceholder: "10115",
    uploadPhotoLabel: "📸 Prześlij zdjęcie",
    uploadPhoto: "Prześlij zdjęcie",
    uploadPhotoDescription: "Kliknij tutaj lub przeciągnij zdjęcie swoich odpadów tutaj",
    analyzeButton: "🔍 Analizuj moje odpady",
    analyzing: "Analizowanie...",
    validPostalCode: "Prawidłowy kod pocztowy",
    invalidPostalCode: "⚠️ Proszę wprowadzić prawidłowy 5-cyfrowy niemiecki kod pocztowy",
    whyImportant: "Dlaczego prawidłowa segregacja odpadów jest ważna?",
    reason1: "Ochrona środowiska poprzez recykling i ponowne wykorzystanie",
    reason2: "Redukcja odpadów składowiskowych i emisji CO2",
    reason3: "Zgodność z niemieckimi prawami środowiskowymi",
    reason4: "Oszczędności kosztów w utylizacji odpadów",
    languageSelector: "Wybierz język",
    analysisComplete: "Analiza Zakończona",
    analysisCompleteDescription: "Oto Twoje instrukcje sortowania",
    analysisError: "Błąd Analizy",
    analysisErrorDescription: "Wystąpił błąd podczas analizy",
    newAnalysis: "Rozpocznij Nową Analizę",
    genericError: "Wystąpił nieoczekiwany błąd. Spróbuj ponownie.",
    detectLocation: "Wykryj Lokalizację",
    geolocationNotSupported: "Geolokalizacja nie jest obsługiwana przez tę przeglądarkę",
    locationPermissionDenied: "Dostęp do lokalizacji został odrzucony",
    locationUnavailable: "Lokalizacja jest niedostępna",
    locationTimeout: "Przekroczono czas wykrywania lokalizacji",
    locationError: "Błąd wykrywania lokalizacji",
    geocodingError: "Błąd określania kodu pocztowego",
    noGermanPostalCodeFound: "Nie znaleziono niemieckiego kodu pocztowego dla tej lokalizacji",
    apiKeyRestrictionError: "Błąd ograniczenia klucza API. Skontaktuj się z administratorem."
  },
  ar: {
    title: "مساعد فرز النفايات",
    subtitle: "فصل النفايات الصحيح في ألمانيا",
    description: "أدخل الرمز البريدي وارفع صورة لنفاياتك. سنساعدك في فرزها بشكل صحيح.",
    postalCodeLabel: "📍 الرمز البريدي",
    postalCodePlaceholder: "10115",
    uploadPhotoLabel: "📸 رفع صورة",
    uploadPhoto: "رفع صورة",
    uploadPhotoDescription: "انقر هنا أو اسحب صورة نفاياتك هنا",
    analyzeButton: "🔍 تحليل نفاياتي",
    analyzing: "جاري التحليل...",
    validPostalCode: "رمز بريدي صحيح",
    invalidPostalCode: "⚠️ يرجى إدخال رمز بريدي ألماني صحيح مكون من 5 أرقام",
    whyImportant: "لماذا فرز النفايات الصحيح مهم؟",
    reason1: "حماية البيئة من خلال إعادة التدوير وإعادة الاستخدام",
    reason2: "تقليل نفايات المكبات وانبعاثات ثاني أكسيد الكربون",
    reason3: "الامتثال لقوانين البيئة الألمانية",
    reason4: "توفير التكاليف في التخلص من النفايات",
    languageSelector: "اختر اللغة",
    analysisComplete: "اكتمل التحليل",
    analysisCompleteDescription: "إليك تعليمات الفرز",
    analysisError: "فشل التحليل",
    analysisErrorDescription: "حدث خطأ أثناء التحليل",
    newAnalysis: "بدء تحليل جديد",
    genericError: "حدث خطأ غير متوقع. يرجى المحاولة مرة أخرى.",
    detectLocation: "تحديد الموقع",
    geolocationNotSupported: "تحديد الموقع الجغرافي غير مدعوم من هذا المتصفح",
    locationPermissionDenied: "تم رفض الوصول إلى الموقع",
    locationUnavailable: "الموقع غير متاح",
    locationTimeout: "انتهت مهلة تحديد الموقع",
    locationError: "خطأ في تحديد الموقع",
    geocodingError: "خطأ في تحديد الرمز البريدي",
    noGermanPostalCodeFound: "لم يتم العثور على رمز بريدي ألماني لهذا الموقع",
    apiKeyRestrictionError: "خطأ في قيود مفتاح API. يرجى الاتصال بالمسؤول."
  },
  ku: {
    title: "Alîkarê Veqetandina Zibilê",
    subtitle: "Veqetandina Rast a Zibilê li Almanyayê",
    description: "Koda xwe ya postê binivîse û wêneyê zibilê xwe bar bike. Em ê alîkariya te bikin ku ew bi rengekî rast veqetînî.",
    postalCodeLabel: "📍 Koda Postê",
    postalCodePlaceholder: "10115",
    uploadPhotoLabel: "📸 Wêne Bar Bike",
    uploadPhoto: "Wêne Bar Bike",
    uploadPhotoDescription: "Li vir bitikîne an wêneyê zibilê xwe li vir bikişîne",
    analyzeButton: "🔍 Zibilê Min Analîz Bike",
    analyzing: "Analîz dike...",
    validPostalCode: "Koda postê ya derbasdar",
    invalidPostalCode: "⚠️ Ji kerema xwe koda postê ya Almanyayê ya 5 hejmarî ya derbasdar binivîse",
    whyImportant: "Çima veqetandina rast a zibilê girîng e?",
    reason1: "Parastina jîngehê bi rêya dووbarekar û dووbarebikaranînê",
    reason2: "Kêmkirina zibilên çalê û belavbûna CO2",
    reason3: "Lêpirsîna yasayên jîngehê yên Almanyayê",
    reason4: "Xilasbûna pere di avêtina zibilê de",
    languageSelector: "Ziman Hilbijêre",
    analysisComplete: "Analîz Temam Bû",
    analysisCompleteDescription: "Li vir rêberiyên veqetandinê ne",
    analysisError: "Analîz Têk Çû",
    analysisErrorDescription: "Di dema analîzê de xeletî çêbû",
    newAnalysis: "Analîzek Nû Dest Pê Bike",
    genericError: "Xeletîyek nenas çêbû. Ji kerema xwe dîsa biceribîne.",
    detectLocation: "Cîh Diyar Bike",
    geolocationNotSupported: "Diyarkirina cîhê ji aliyê vê gerokê ve nayê piştgirîkirin",
    locationPermissionDenied: "Gihîştina cîhê hat redkirin",
    locationUnavailable: "Cîh berdest nîne",
    locationTimeout: "Dema diyarkirina cîhê qediya",
    locationError: "Xeletî di diyarkirina cîhê de",
    geocodingError: "Xeletî di diyarkirina koda postê de",
    noGermanPostalCodeFound: "Ji bo vî cîhî koda postê ya Almanyayê nehat dîtin",
    apiKeyRestrictionError: "Xeletîya sînorkirina mifteya API. Ji kerema xwe bi rêveberê re têkilî daynin."
  },
  it: {
    title: "Assistente per la Raccolta Differenziata",
    subtitle: "Corretta separazione dei rifiuti in Germania",
    description: "Inserisci il tuo codice postale e carica una foto dei tuoi rifiuti. Ti aiuteremo a smaltirli correttamente.",
    postalCodeLabel: "📍 Codice Postale",
    postalCodePlaceholder: "10115",
    uploadPhotoLabel: "📸 Carica Foto",
    uploadPhoto: "Carica Foto",
    uploadPhotoDescription: "Clicca qui o trascina una foto dei tuoi rifiuti qui",
    analyzeButton: "🔍 Analizza i Miei Rifiuti",
    analyzing: "Analizzando...",
    validPostalCode: "Codice postale valido",
    invalidPostalCode: "⚠️ Inserisci un codice postale tedesco valido di 5 cifre",
    whyImportant: "Perché la corretta raccolta differenziata è importante?",
    reason1: "Protezione ambientale attraverso riciclaggio e riutilizzo",
    reason2: "Riduzione dei rifiuti in discarica e delle emissioni di CO2",
    reason3: "Conformità alle leggi ambientali tedesche",
    reason4: "Risparmio sui costi di smaltimento rifiuti",
    languageSelector: "Seleziona Lingua",
    analysisComplete: "Analisi Completata",
    analysisCompleteDescription: "Ecco le tue istruzioni per lo smaltimento",
    analysisError: "Analisi Fallita",
    analysisErrorDescription: "Si è verificato un errore durante l'analisi",
    newAnalysis: "Inizia Nuova Analisi",
    genericError: "Si è verificato un errore imprevisto. Riprova.",
    detectLocation: "Rileva Posizione",
    geolocationNotSupported: "La geolocalizzazione non è supportata da questo browser",
    locationPermissionDenied: "L'accesso alla posizione è stato negato",
    locationUnavailable: "La posizione non è disponibile",
    locationTimeout: "Timeout rilevamento posizione",
    locationError: "Errore nel rilevamento della posizione",
    geocodingError: "Errore nella determinazione del codice postale",
    noGermanPostalCodeFound: "Nessun codice postale tedesco trovato per questa posizione",
    apiKeyRestrictionError: "Errore di restrizione chiave API. Contatta l'amministratore."
  },
  bs: {
    title: "Asistent za Sortiranje Otpada",
    subtitle: "Pravilno Razvrstavanje Otpada u Njemačkoj",
    description: "Unesite svoj poštanski broj i učitajte fotografiju svog otpada. Pomoći ćemo vam da ga pravilno razvrstite.",
    postalCodeLabel: "📍 Poštanski broj",
    postalCodePlaceholder: "10115",
    uploadPhotoLabel: "📸 Učitaj Fotografiju",
    uploadPhoto: "Učitaj Fotografiju",
    uploadPhotoDescription: "Kliknite ovdje ili povucite fotografiju svog otpada ovdje",
    analyzeButton: "🔍 Analiziraj Moj Otpad",
    analyzing: "Analiziranje...",
    validPostalCode: "Važeći poštanski broj",
    invalidPostalCode: "⚠️ Molimo unesite važeći 5-cifreni njemački poštanski broj",
    whyImportant: "Zašto je pravilno sortiranje otpada važno?",
    reason1: "Zaštita okoliša kroz recikliranje i ponovnu upotrebu",
    reason2: "Smanjenje otpada na deponijama i CO2 emisija",
    reason3: "Pridržavanje njemačkih zakona o okolišu",
    reason4: "Uštede troškova u zbrinjavanju otpada",
    languageSelector: "Odaberite Jezik",
    analysisComplete: "Analiza Završena",
    analysisCompleteDescription: "Evo vaših instrukcija za sortiranje",
    analysisError: "Analiza Neuspješna",
    analysisErrorDescription: "Došlo je do greške tokom analize",
    newAnalysis: "Počni Novu Analizu",
    genericError: "Došlo je do neočekivane greške. Molimo pokušajte ponovo.",
    detectLocation: "Odredi Lokaciju",
    geolocationNotSupported: "Geolokacija nije podržana od strane ovog preglednika",
    locationPermissionDenied: "Pristup lokaciji je odbačen",
    locationUnavailable: "Lokacija nije dostupna",
    locationTimeout: "Istek vremena za određivanje lokacije",
    locationError: "Greška u određivanju lokacije",
    geocodingError: "Greška u određivanju poštanskog broja",
    noGermanPostalCodeFound: "Njemački poštanski broj nije pronađen za ovu lokaciju",
    apiKeyRestrictionError: "Greška ograničenja API ključa. Molimo kontaktirajte administratora."
  },
  hr: {
    title: "Asistent za Sortiranje Otpada",
    subtitle: "Pravilno Razvrstavanje Otpada u Njemačkoj",
    description: "Unesite svoj poštanski broj i učitajte fotografiju svog otpada. Pomoći ćemo vam da ga pravilno razvrstite.",
    postalCodeLabel: "📍 Poštanski broj",
    postalCodePlaceholder: "10115",
    uploadPhotoLabel: "📸 Učitaj Fotografiju",
    uploadPhoto: "Učitaj Fotografiju",
    uploadPhotoDescription: "Kliknite ovdje ili povucite fotografiju svog otpada ovdje",
    analyzeButton: "🔍 Analiziraj Moj Otpad",
    analyzing: "Analiziranje...",
    validPostalCode: "Važeći poštanski broj",
    invalidPostalCode: "⚠️ Molimo unesite važeći 5-znamenkasti njemački poštanski broj",
    whyImportant: "Zašto je pravilno sortiranje otpada važno?",
    reason1: "Zaštita okoliša kroz recikliranje i ponovnu upotrebu",
    reason2: "Smanjenje otpada na odlagalištima i CO2 emisija",
    reason3: "Pridržavanje njemačkih zakona o okolišu",
    reason4: "Uštede troškova u zbrinjavanju otpada",
    languageSelector: "Odaberite Jezik",
    analysisComplete: "Analiza Završena",
    analysisCompleteDescription: "Evo vaših instrukcija za sortiranje",
    analysisError: "Analiza Neuspješna",
    analysisErrorDescription: "Došlo je do greške tijekom analize",
    newAnalysis: "Počni Novu Analizu",
    genericError: "Došlo je do neočekivane greške. Molimo pokušajte ponovo.",
    detectLocation: "Odredi Lokaciju",
    geolocationNotSupported: "Geolokacija nije podržana od strane ovog preglednika",
    locationPermissionDenied: "Pristup lokaciji je odbačen",
    locationUnavailable: "Lokacija nije dostupna",
    locationTimeout: "Istek vremena za određivanje lokacije",
    locationError: "Greška u određivanju lokacije",
    geocodingError: "Greška u određivanju poštanskog broja",
    noGermanPostalCodeFound: "Njemački poštanski broj nije pronađen za ovu lokaciju",
    apiKeyRestrictionError: "Greška ograničenja API ključa. Molimo kontaktirajte administratora."
  },
  sr: {
    title: "Асистент за Сортирање Отпада",
    subtitle: "Правилно Разврставање Отпада у Немачкој",
    description: "Унесите свој поштански број и учитајте фотографију свог отпада. Помоћи ћемо вам да га правилно развrstите.",
    postalCodeLabel: "📍 Поштански број",
    postalCodePlaceholder: "10115",
    uploadPhotoLabel: "📸 Учитај Фотографију",
    uploadPhoto: "Учитај Фотографију",
    uploadPhotoDescription: "Кликните овде или повуците фотографију свог отпада овде",
    analyzeButton: "🔍 Анализирај Мој Отпад",
    analyzing: "Анализирање...",
    validPostalCode: "Важећи поштански број",
    invalidPostalCode: "⚠️ Молимо унесите важећи 5-цифрени немачки поштански број",
    whyImportant: "Зашто је правилно сортирање отпада важно?",
    reason1: "Заштита животне средине кроз рециклирање и поновну употребу",
    reason2: "Смањење отпада на депонијама и CO2 емисија",
    reason3: "Придржавање немачких закона о животној средини",
    reason4: "Уштеде трошкова у збрињавању отпада",
    languageSelector: "Одаберите Језик",
    analysisComplete: "Анализа Завршена",
    analysisCompleteDescription: "Ево ваших инструкција за сортирање",
    analysisError: "Анализа Неуспешна",
    analysisErrorDescription: "Дошло је до грешке током анализе",
    newAnalysis: "Почни Нову Анализу",
    genericError: "Дошло је до неочекиване грешке. Молимо покушајте поново.",
    detectLocation: "Одреди Локацију",
    geolocationNotSupported: "Геолокација није подржана од стране овог прегледника",
    locationPermissionDenied: "Приступ локацији је одбачен",
    locationUnavailable: "Локација није доступна",
    locationTimeout: "Истек времена за одређивање локације",
    locationError: "Грешка у одређивању локације",
    geocodingError: "Грешка у одређивању поштанског броја",
    noGermanPostalCodeFound: "Немачки поштански број није пронађен за ову локацију",
    apiKeyRestrictionError: "Грешка ограничења API кључа. Молимо контактирајте администратора."
  },
  ro: {
    title: "Asistent pentru Sortarea Deșeurilor",
    subtitle: "Separarea Corectă a Deșeurilor în Germania",
    description: "Introduceți codul poștal și încărcați o fotografie a deșeurilor. Vă vom ajuta să le sortați corect.",
    postalCodeLabel: "📍 Cod poștal",
    postalCodePlaceholder: "10115",
    uploadPhotoLabel: "📸 Încărcați Fotografia",
    uploadPhoto: "Încărcați Fotografia",
    uploadPhotoDescription: "Faceți clic aici sau trageți o fotografie a deșeurilor aici",
    analyzeButton: "🔍 Analizați Deșeurile Mele",
    analyzing: "Analizare...",
    validPostalCode: "Cod poștal valid",
    invalidPostalCode: "⚠️ Vă rugăm să introduceți un cod poștal german valid de 5 cifre",
    whyImportant: "De ce este importantă sortarea corectă a deșeurilor?",
    reason1: "Protecția mediului prin reciclare și reutilizare",
    reason2: "Reducerea deșeurilor de la groapa de gunoi și emisiilor de CO2",
    reason3: "Respectarea legilor de mediu germane",
    reason4: "Economii de costuri în eliminarea deșeurilor",
    languageSelector: "Selectați Limba",
    analysisComplete: "Analiza Completă",
    analysisCompleteDescription: "Iată instrucțiunile de sortare",
    analysisError: "Analiza Eșuată",
    analysisErrorDescription: "A apărut o eroare în timpul analizei",
    newAnalysis: "Începeți Analiza Nouă",
    genericError: "A apărut o eroare neașteptată. Vă rugăm să încercați din nou.",
    detectLocation: "Detectează Locația",
    geolocationNotSupported: "Geolocația nu este suportată de acest browser",
    locationPermissionDenied: "Accesul la locație a fost refuzat",
    locationUnavailable: "Locația nu este disponibilă",
    locationTimeout: "Timeout detectare locație",
    locationError: "Eroare la detectarea locației",
    geocodingError: "Eroare la determinarea codului poștal",
    noGermanPostalCodeFound: "Nu s-a găsit cod poștal german pentru această locație",
    apiKeyRestrictionError: "Eroare de restricție cheie API. Vă rugăm să contactați administratorul."
  },
  el: {
    title: "Βοηθός Διαχωρισμού Απορριμμάτων",
    subtitle: "Σωστός Διαχωρισμός Απορριμμάτων στη Γερμανία",
    description: "Εισάγετε τον ταχυδρομικό σας κώδικα και ανεβάστε μια φωτογραφία των απορριμμάτων σας. Θα σας βοηθήσουμε να τα διαχωρίσετε σωστά.",
    postalCodeLabel: "📍 Ταχυδρομικός κώδικας",
    postalCodePlaceholder: "10115",
    uploadPhotoLabel: "📸 Ανέβασμα Φωτογραφίας",
    uploadPhoto: "Ανέβασμα Φωτογραφίας",
    uploadPhotoDescription: "Κάντε κλικ εδώ ή σύρετε μια φωτογραφία των απορριμμάτων σας εδώ",
    analyzeButton: "🔍 Αναλύστε τα Απορρίμματά μου",
    analyzing: "Ανάλυση...",
    validPostalCode: "Έγκυρος ταχυδρομικός κώδικας",
    invalidPostalCode: "⚠️ Παρακαλώ εισάγετε έναν έγκυρο 5ψήφιο γερμανικό ταχυδρομικό κώδικα",
    whyImportant: "Γιατί είναι σημαντικός ο σωστός διαχωρισμός απορριμμάτων;",
    reason1: "Προστασία περιβάλλοντος μέσω ανακύκλωσης και επαναχρησιμοποίησης",
    reason2: "Μείωση απορριμμάτων ΧΥΤΑ και εκπομπών CO2",
    reason3: "Συμμόρφωση με τους γερμανικούς περιβαλλοντικούς νόμους",
    reason4: "Εξοικονόμηση κόστους στη διάθεση απορριμμάτων",
    languageSelector: "Επιλέξτε Γλώσσα",
    analysisComplete: "Ανάλυση Ολοκληρώθηκε",
    analysisCompleteDescription: "Εδώ είναι οι οδηγίες διαχωρισμού σας",
    analysisError: "Η Ανάλυση Απέτυχε",
    analysisErrorDescription: "Προέκυψε σφάλμα κατά την ανάλυση",
    newAnalysis: "Ξεκινήστε Νέα Ανάλυση",
    genericError: "Προέκυψε απροσδόκητο σφάλμα. Παρακαλώ δοκιμάστε ξανά.",
    detectLocation: "Εντοπισμός Τοποθεσίας",
    geolocationNotSupported: "Ο γεωεντοπισμός δεν υποστηρίζεται από αυτόν τον περιηγητή",
    locationPermissionDenied: "Η πρόσβαση στην τοποθεσία απορρίφθηκε",
    locationUnavailable: "Η τοποθεσία δεν είναι διαθέσιμη",
    locationTimeout: "Λήξη χρόνου εντοπισμού τοποθεσίας",
    locationError: "Σφάλμα εντοπισμού τοποθεσίας",
    geocodingError: "Σφάλμα προσδιορισμού ταχυδρομικού κώδικα",
    noGermanPostalCodeFound: "Δεν βρέθηκε γερμανικός ταχυδρομικός κώδικας για αυτήν την τοποθεσία",
    apiKeyRestrictionError: "Σφάλμα περιορισμού κλειδιού API. Παρακαλώ επικοινωνήστε με τον διαχειριστή."
  },
  es: {
    title: "Asistente de Clasificación de Residuos",
    subtitle: "Separación Correcta de Residuos en Alemania",
    description: "Ingrese su código postal y suba una foto de sus residuos. Le ayudaremos a clasificarlos correctamente.",
    postalCodeLabel: "📍 Código postal",
    postalCodePlaceholder: "10115",
    uploadPhotoLabel: "📸 Subir Foto",
    uploadPhoto: "Subir Foto",
    uploadPhotoDescription: "Haga clic aquí o arrastre una foto de sus residuos aquí",
    analyzeButton: "🔍 Analizar Mis Residuos",
    analyzing: "Analizando...",
    validPostalCode: "Código postal válido",
    invalidPostalCode: "⚠️ Por favor ingrese un código postal alemán válido de 5 dígitos",
    whyImportant: "¿Por qué es importante la clasificación correcta de residuos?",
    reason1: "Protección ambiental a través del reciclaje y reutilización",
    reason2: "Reducción de residuos de vertedero y emisiones de CO2",
    reason3: "Cumplimiento de las leyes ambientales alemanas",
    reason4: "Ahorro de costos en la eliminación de residuos",
    languageSelector: "Seleccionar Idioma",
    analysisComplete: "Análisis Completo",
    analysisCompleteDescription: "Aquí están sus instrucciones de clasificación",
    analysisError: "Análisis Fallido",
    analysisErrorDescription: "Ocurrió un error durante el análisis",
    newAnalysis: "Iniciar Nuevo Análisis",
    genericError: "Ocurrió un error inesperado. Por favor intente de nuevo.",
    detectLocation: "Detectar Ubicación",
    geolocationNotSupported: "La geolocalización no es compatible con este navegador",
    locationPermissionDenied: "Se denegó el acceso a la ubicación",
    locationUnavailable: "La ubicación no está disponible",
    locationTimeout: "Tiempo de espera de detección de ubicación agotado",
    locationError: "Error al detectar la ubicación",
    geocodingError: "Error al determinar el código postal",
    noGermanPostalCodeFound: "No se encontró código postal alemán para esta ubicación",
    apiKeyRestrictionError: "Error de restricción de clave API. Por favor contacte al administrador."
  },
  fr: {
    title: "Assistant de Tri des Déchets",
    subtitle: "Séparation Correcte des Déchets en Allemagne",
    description: "Entrez votre code postal et téléchargez une photo de vos déchets. Nous vous aiderons à les trier correctement.",
    postalCodeLabel: "📍 Code postal",
    postalCodePlaceholder: "10115",
    uploadPhotoLabel: "📸 Télécharger Photo",
    uploadPhoto: "Télécharger Photo",
    uploadPhotoDescription: "Cliquez ici ou faites glisser une photo de vos déchets ici",
    analyzeButton: "🔍 Analyser Mes Déchets",
    analyzing: "Analyse en cours...",
    validPostalCode: "Code postal valide",
    invalidPostalCode: "⚠️ Veuillez entrer un code postal allemand valide à 5 chiffres",
    whyImportant: "Pourquoi le tri correct des déchets est-il important?",
    reason1: "Protection de l'environnement par le recyclage et la réutilisation",
    reason2: "Réduction des déchets d'enfouissement et des émissions de CO2",
    reason3: "Conformité aux lois environnementales allemandes",
    reason4: "Économies de coûts dans l'élimination des déchets",
    languageSelector: "Sélectionner la Langue",
    analysisComplete: "Analyse Terminée",
    analysisCompleteDescription: "Voici vos instructions de tri",
    analysisError: "Échec de l'Analyse",
    analysisErrorDescription: "Une erreur s'est produite lors de l'analyse",
    newAnalysis: "Commencer une Nouvelle Analyse",
    genericError: "Une erreur inattendue s'est produite. Veuillez réessayer.",
    detectLocation: "Détecter l'Emplacement",
    geolocationNotSupported: "La géolocalisation n'est pas prise en charge par ce navigateur",
    locationPermissionDenied: "L'accès à l'emplacement a été refusé",
    locationUnavailable: "L'emplacement n'est pas disponible",
    locationTimeout: "Délai d'attente de détection d'emplacement dépassé",
    locationError: "Erreur de détection d'emplacement",
    geocodingError: "Erreur de détermination du code postal",
    noGermanPostalCodeFound: "Aucun code postal allemand trouvé pour cet emplacement",
    apiKeyRestrictionError: "Erreur de restriction de clé API. Veuillez contacter l'administrateur."
  },
  hi: {
    title: "कचरा छंटाई सहायक",
    subtitle: "जर्मनी में उचित कचरा पृथक्करण",
    description: "अपना पोस्टल कोड दर्ज करें और अपने कचरे की एक तस्वीर अपलोड करें। हम आपको इसे सही तरीके से छांटने में मदद करेंगे।",
    postalCodeLabel: "📍 पोस्टल कोड",
    postalCodePlaceholder: "10115",
    uploadPhotoLabel: "📸 फोटो अपलोड करें",
    uploadPhoto: "फोटो अपलोड करें",
    uploadPhotoDescription: "यहाँ क्लिक करें या अपने कचरे की एक तस्वीर यहाँ खींचें",
    analyzeButton: "🔍 मेरे कचरे का विश्लेषण करें",
    analyzing: "विश्लेषण कर रहे हैं...",
    validPostalCode: "वैध पोस्टल कोड",
    invalidPostalCode: "⚠️ कृपया एक वैध 5 अंकीय जर्मन पोस्टल कोड दर्ज करें",
    whyImportant: "उचित कचरा छंटाई क्यों महत्वपूर्ण है?",
    reason1: "पुनर्चक्रण और पुन: उपयोग के माध्यम से पर्यावरण संरक्षण",
    reason2: "लैंडफिल कचरे और CO2 उत्सर्जन में कमी",
    reason3: "जर्मन पर्यावरण कानूनों का अनुपालन",
    reason4: "कचरा निपटान में लागत बचत",
    languageSelector: "भाषा का चयन करें",
    analysisComplete: "विश्लेषण पूर्ण",
    analysisCompleteDescription: "यहाँ आपके छंटाई निर्देश हैं",
    analysisError: "विश्लेषण असफल",
    analysisErrorDescription: "विश्लेषण के दौरान एक त्रुटि हुई",
    newAnalysis: "नया विश्लेषण शुरू करें",
    genericError: "एक अप्रत्याशित त्रुटि हुई। कृपया पुनः प्रयास करें।",
    detectLocation: "स्थान का पता लगाएं",
    geolocationNotSupported: "इस ब्राउज़र द्वारा भौगोलिक स्थान समर्थित नहीं है",
    locationPermissionDenied: "स्थान पहुंच से इनकार कर दिया गया",
    locationUnavailable: "स्थान उपलब्ध नहीं है",
    locationTimeout: "स्थान का पता लगाने का समय समाप्त",
    locationError: "स्थान का पता लगाने में त्रुटि",
    geocodingError: "पोस्टल कोड निर्धारित करने में त्रुटि",
    noGermanPostalCodeFound: "इस स्थान के लिए कोई जर्मन पोस्टल कोड नहीं मिला",
    apiKeyRestrictionError: "API कुंजी प्रतिबंध त्रुटि। कृपया व्यवस्थापक से संपर्क करें।"
  },
  ur: {
    title: "کچرا چھانٹنے کا مددگار",
    subtitle: "جرمنی میں صحیح کچرا الگ کرنا",
    description: "اپنا پوسٹل کوڈ داخل کریں اور اپنے کچرے کی تصویر اپ لوڈ کریں۔ ہم آپ کو اسے صحیح طریقے سے چھانٹنے میں مدد کریں گے۔",
    postalCodeLabel: "📍 پوسٹل کوڈ",
    postalCodePlaceholder: "10115",
    uploadPhotoLabel: "📸 تصویر اپ لوڈ کریں",
    uploadPhoto: "تصویر اپ لوڈ کریں",
    uploadPhotoDescription: "یہاں کلک کریں یا اپنے کچرے کی تصویر یہاں کھینچیں",
    analyzeButton: "🔍 میرے کچرے کا تجزیہ کریں",
    analyzing: "تجزیہ کر رہے ہیں...",
    validPostalCode: "درست پوسٹل کوڈ",
    invalidPostalCode: "⚠️ براہ کرم ایک درست 5 ہندسوں کا جرمن پوسٹل کوڈ داخل کریں",
    whyImportant: "صحیح کچرا چھانٹنا کیوں اہم ہے؟",
    reason1: "ری سائیکلنگ اور دوبارہ استعمال کے ذریعے ماحولیات کا تحفظ",
    reason2: "لینڈ فل کچرے اور CO2 اخراج میں کمی",
    reason3: "جرمن ماحولیاتی قوانین کی تعمیل",
    reason4: "کچرا ٹھکانے لگانے میں لاگت کی بچت",
    languageSelector: "زبان منتخب کریں",
    analysisComplete: "تجزیہ مکمل",
    analysisCompleteDescription: "یہاں آپ کی چھانٹنے کی ہدایات ہیں",
    analysisError: "تجزیہ ناکام",
    analysisErrorDescription: "تجزیے کے دوران ایک خرابی ہوئی",
    newAnalysis: "نیا تجزیہ شروع کریں",
    genericError: "ایک غیر متوقع خرابی ہوئی۔ براہ کرم دوبارہ کوشش کریں۔",
    detectLocation: "مقام کا تعین کریں",
    geolocationNotSupported: "اس براؤزر کے ذریعے جغرافیائی مقام کی حمایت نہیں کی جاتی",
    locationPermissionDenied: "مقام تک رسائی سے انکار کر دیا گیا",
    locationUnavailable: "مقام دستیاب نہیں ہے",
    locationTimeout: "مقام کا تعین کرنے کا وقت ختم",
    locationError: "مقام کا تعین کرنے میں خرابی",
    geocodingError: "پوسٹل کوڈ کا تعین کرنے میں خرابی",
    noGermanPostalCodeFound: "اس مقام کے لیے کوئی جرمن پوسٹل کوڈ نہیں ملا",
    apiKeyRestrictionError: "API کلید پابندی کی خرابی۔ براہ کرم منتظم سے رابطہ کریں۔"
  },
  vi: {
    title: "Trợ Lý Phân Loại Rác",
    subtitle: "Phân Loại Rác Đúng Cách tại Đức",
    description: "Nhập mã bưu điện của bạn và tải lên một bức ảnh về rác của bạn. Chúng tôi sẽ giúp bạn phân loại đúng cách.",
    postalCodeLabel: "📍 Mã bưu điện",
    postalCodePlaceholder: "10115",
    uploadPhotoLabel: "📸 Tải Lên Ảnh",
    uploadPhoto: "Tải Lên Ảnh",
    uploadPhotoDescription: "Nhấp vào đây hoặc kéo một bức ảnh về rác của bạn vào đây",
    analyzeButton: "🔍 Phân Tích Rác Của Tôi",
    analyzing: "Đang phân tích...",
    validPostalCode: "Mã bưu điện hợp lệ",
    invalidPostalCode: "⚠️ Vui lòng nhập mã bưu điện Đức hợp lệ gồm 5 chữ số",
    whyImportant: "Tại sao phân loại rác đúng cách lại quan trọng?",
    reason1: "Bảo vệ môi trường thông qua tái chế và tái sử dụng",
    reason2: "Giảm rác thải bãi rác và phát thải CO2",
    reason3: "Tuân thủ luật môi trường của Đức",
    reason4: "Tiết kiệm chi phí trong việc xử lý rác thải",
    languageSelector: "Chọn Ngôn Ngữ",
    analysisComplete: "Phân Tích Hoàn Thành",
    analysisCompleteDescription: "Đây là hướng dẫn phân loại của bạn",
    analysisError: "Phân Tích Thất Bại",
    analysisErrorDescription: "Đã xảy ra lỗi trong quá trình phân tích",
    newAnalysis: "Bắt Đầu Phân Tích Mới",
    genericError: "Đã xảy ra lỗi không mong muốn. Vui lòng thử lại.",
    detectLocation: "Phát Hiện Vị Trí",
    geolocationNotSupported: "Định vị địa lý không được hỗ trợ bởi trình duyệt này",
    locationPermissionDenied: "Quyền truy cập vị trí đã bị từ chối",
    locationUnavailable: "Vị trí không khả dụng",
    locationTimeout: "Hết thời gian phát hiện vị trí",
    locationError: "Lỗi phát hiện vị trí",
    geocodingError: "Lỗi xác định mã bưu điện",
    noGermanPostalCodeFound: "Không tìm thấy mã bưu điện Đức cho vị trí này",
    apiKeyRestrictionError: "Lỗi hạn chế khóa API. Vui lòng liên hệ quản trị viên."
  },
  zh: {
    title: "垃圾分类助手",
    subtitle: "德国正确垃圾分类",
    description: "输入您的邮政编码并上传您垃圾的照片。我们将帮助您正确分类。",
    postalCodeLabel: "📍 邮政编码",
    postalCodePlaceholder: "10115",
    uploadPhotoLabel: "📸 上传照片",
    uploadPhoto: "上传照片",
    uploadPhotoDescription: "点击这里或将您垃圾的照片拖到这里",
    analyzeButton: "🔍 分析我的垃圾",
    analyzing: "分析中...",
    validPostalCode: "有效邮政编码",
    invalidPostalCode: "⚠️ 请输入有效的5位德国邮政编码",
    whyImportant: "为什么正确的垃圾分类很重要？",
    reason1: "通过回收和再利用保护环境",
    reason2: "减少垃圾填埋场废物和二氧化碳排放",
    reason3: "遵守德国环境法律",
    reason4: "节省废物处理成本",
    languageSelector: "选择语言",
    analysisComplete: "分析完成",
    analysisCompleteDescription: "这是您的分类说明",
    analysisError: "分析失败",
    analysisErrorDescription: "分析过程中发生错误",
    newAnalysis: "开始新分析",
    genericError: "发生意外错误。请重试。",
    detectLocation: "检测位置",
    geolocationNotSupported: "此浏览器不支持地理定位",
    locationPermissionDenied: "位置访问被拒绝",
    locationUnavailable: "位置不可用",
    locationTimeout: "位置检测超时",
    locationError: "位置检测错误",
    geocodingError: "确定邮政编码时出错",
    noGermanPostalCodeFound: "未找到此位置的德国邮政编码",
    apiKeyRestrictionError: "API密钥限制错误。请联系管理员。"
  },
  fa: {
    title: "دستیار تفکیک زباله",
    subtitle: "تفکیک صحیح زباله در آلمان",
    description: "کد پستی خود را وارد کنید و عکسی از زباله‌هایتان آپلود کنید. ما به شما کمک می‌کنیم تا آن‌ها را به درستی تفکیک کنید.",
    postalCodeLabel: "📍 کد پستی",
    postalCodePlaceholder: "10115",
    uploadPhotoLabel: "📸 آپلود عکس",
    uploadPhoto: "آپلود عکس",
    uploadPhotoDescription: "اینجا کلیک کنید یا عکس زباله‌هایتان را اینجا بکشید",
    analyzeButton: "🔍 تجزیه و تحلیل زباله‌های من",
    analyzing: "در حال تجزیه و تحلیل...",
    validPostalCode: "کد پستی معتبر",
    invalidPostalCode: "⚠️ لطفاً یک کد پستی آلمانی معتبر 5 رقمی وارد کنید",
    whyImportant: "چرا تفکیک صحیح زباله مهم است؟",
    reason1: "حفاظت از محیط زیست از طریق بازیافت و استفاده مجدد",
    reason2: "کاهش زباله‌های دفن و انتشار CO2",
    reason3: "رعایت قوانین زیست‌محیطی آلمان",
    reason4: "صرفه‌جویی در هزینه‌های دفع زباله",
    languageSelector: "انتخاب زبان",
    analysisComplete: "تجزیه و تحلیل کامل شد",
    analysisCompleteDescription: "اینجا دستورالعمل‌های تفکیک شما است",
    analysisError: "تجزیه و تحلیل ناموفق",
    analysisErrorDescription: "خطایی در طول تجزیه و تحلیل رخ داد",
    newAnalysis: "شروع تجزیه و تحلیل جدید",
    genericError: "خطای غیرمنتظره‌ای رخ داد. لطفاً دوباره تلاش کنید.",
    detectLocation: "تشخیص موقعیت",
    geolocationNotSupported: "موقعیت‌یابی جغرافیایی توسط این مرورگر پشتیبانی نمی‌شود",
    locationPermissionDenied: "دسترسی به موقعیت رد شد",
    locationUnavailable: "موقعیت در دسترس نیست",
    locationTimeout: "زمان تشخیص موقعیت به پایان رسید",
    locationError: "خطا در تشخیص موقعیت",
    geocodingError: "خطا در تعیین کد پستی",
    noGermanPostalCodeFound: "کد پستی آلمانی برای این موقعیت یافت نشد",
    apiKeyRestrictionError: "خطای محدودیت کلید API. لطفاً با مدیر تماس بگیرید."
  },
  ps: {
    title: "د کثافاتو د جلا کولو مرستیال",
    subtitle: "په آلمان کې د کثافاتو سمه جلا کول",
    description: "خپل پوستي کوډ ولیکئ او د خپلو کثافاتو انځور پورته کړئ. موږ به ستاسو سره د دوی د سمه جلا کولو کې مرسته وکړو.",
    postalCodeLabel: "📍 پوستي کوډ",
    postalCodePlaceholder: "10115",
    uploadPhotoLabel: "📸 انځور پورته کړئ",
    uploadPhoto: "انځور پورته کړئ",
    uploadPhotoDescription: "دلته کلیک وکړئ یا د خپلو کثافاتو انځور دلته راوکشئ",
    analyzeButton: "🔍 زموږ کثافات تحلیل کړئ",
    analyzing: "تحلیل کوي...",
    validPostalCode: "سمه پوستي کوډ",
    invalidPostalCode: "⚠️ مهرباني وکړئ د آلمان سمه 5 شمیرې پوستي کوډ ولیکئ",
    whyImportant: "ولې د کثافاتو سمه جلا کول مهم دي؟",
    reason1: "د بیا کارولو او بیا کارونې له لارې د چاپیریال ساتنه",
    reason2: "د ځمکې د ډکولو کثافاتو او د CO2 د خپرولو کمول",
    reason3: "د آلمان د چاپیریال د قوانینو تعقیبول",
    reason4: "د کثافاتو د لرې کولو په لګښتونو کې سپمول",
    languageSelector: "ژبه وټاکئ",
    analysisComplete: "تحلیل بشپړ شو",
    analysisCompleteDescription: "دلته ستاسو د جلا کولو لارښوونې دي",
    analysisError: "تحلیل ناکام شو",
    analysisErrorDescription: "د تحلیل پر مهال یوه ستونزه رامنځته شوه",
    newAnalysis: "نوی تحلیل پیل کړئ",
    genericError: "یوه غیر متوقعه ستونزه رامنځته شوه. مهرباني وکړئ بیا هڅه وکړئ.",
    detectLocation: "ځای وپیژنئ",
    geolocationNotSupported: "د ځای پیژندنه د دغه براوزر لخوا نه ملاتړ کیږي",
    locationPermissionDenied: "د ځای ته لاسرسي رد شو",
    locationUnavailable: "ځای شتون نلري",
    locationTimeout: "د ځای پیژندنې وخت ختم شو",
    locationError: "د ځای پیژندنې کې ستونزه",
    geocodingError: "د پوستي کوډ ټاکلو کې ستونزه",
    noGermanPostalCodeFound: "د دغه ځای لپاره د آلمان پوستي کوډ ونه موندل شو",
    apiKeyRestrictionError: "د API کیلي محدودیت ستونزه. مهرباني وکړئ د اداري سره اړیکه ونیسئ."
  },
  ta: {
    title: "குப்பை வகைப்படுத்தும் உதவியாளர்",
    subtitle: "ஜெர்மனியில் சரியான குப்பை பிரிப்பு",
    description: "உங்கள் அஞ்சல் குறியீட்டை உள்ளிட்டு உங்கள் குப்பையின் புகைப்படத்தை பதிவேற்றவும். அதை சரியாக வகைப்படுத்த நாங்கள் உங்களுக்கு உதவுவோம்.",
    postalCodeLabel: "📍 அஞ்சல் குறியீடு",
    postalCodePlaceholder: "10115",
    uploadPhotoLabel: "📸 புகைப்படத்தை பதிவேற்றவும்",
    uploadPhoto: "புகைப்படத்தை பதிவேற்றவும்",
    uploadPhotoDescription: "இங்கே கிளிக் செய்யவும் அல்லது உங்கள் குப்பையின் புகைப்படத்தை இங்கே இழுக்கவும்",
    analyzeButton: "🔍 என் குப்பையை பகுப்பாய்வு செய்யவும்",
    analyzing: "பகுப்பாய்வு செய்கிறது...",
    validPostalCode: "செல்லுபடியாகும் அஞ்சல் குறியீடு",
    invalidPostalCode: "⚠️ தயவுசெய்து செல்லுபடியாகும் 5 இலக்க ஜெர்மன் அஞ்சல் குறியீட்டை உள்ளிடவும்",
    whyImportant: "சரியான குப்பை வகைப்படுத்துதல் ஏன் முக்கியம்?",
    reason1: "மறுசுழற்சி மற்றும் மறுபயன்பாடு மூலம் சுற்றுச்சூழல் பாதுகாப்பு",
    reason2: "நிலப்பரப்பு குப்பை மற்றும் CO2 உமிழ்வுகளை குறைத்தல்",
    reason3: "ஜெர்மன் சுற்றுச்சூழல் சட்டங்களுக்கு இணக்கம்",
    reason4: "குப்பை அகற்றலில் செலவு சேமிப்பு",
    languageSelector: "மொழியைத் தேர்ந்தெடுக்கவும்",
    analysisComplete: "பகுப்பாய்வு முடிந்தது",
    analysisCompleteDescription: "இங்கே உங்கள் வகைப்படுத்தும் வழிமுறைகள்",
    analysisError: "பகுப்பாய்வு தோல்வியடைந்தது",
    analysisErrorDescription: "பகுப்பாய்வின் போது பிழை ஏற்பட்டது",
    newAnalysis: "புதிய பகுப்பாய்வைத் தொடங்கவும்",
    genericError: "எதிர்பாராத பிழை ஏற்பட்டது. தயவுசெய்து மீண்டும் முயற்சிக்கவும்.",
    detectLocation: "இருப்பிடத்தைக் கண்டறியவும்",
    geolocationNotSupported: "இந்த உலாவியால் புவியிருப்பிடம் ஆதரிக்கப்படவில்லை",
    locationPermissionDenied: "இருப்பிட அணுகல் மறுக்கப்பட்டது",
    locationUnavailable: "இருப்பிடம் கிடைக்கவில்லை",
    locationTimeout: "இருப்பிடக் கண்டறிதல் நேரம் முடிந்தது",
    locationError: "இருப்பிடத்தைக் கண்டறிவதில் பிழை",
    geocodingError: "அஞ்சல் குறியீட்டை தீர்மானிப்பதில் பிழை",
    noGermanPostalCodeFound: "இந்த இருப்பிடத்திற்கு ஜெர்மன் அஞ்சல் குறியீடு கிடைக்கவில்லை",
    apiKeyRestrictionError: "API விசை கட்டுப்பாடு பிழை. தயவுசெய்து நிர்வாகியைத் தொடர்பு கொள்ளவும்."
  },
  sq: {
    title: "Asistenti i Ndarjes së Mbeturinave",
    subtitle: "Ndarja e Duhur e Mbeturinave në Gjermani",
    description: "Vendosni kodin tuaj postar dhe ngarkoni një fotografi të mbeturinave tuaja. Do t'ju ndihmojmë t'i ndani në mënyrë të duhur.",
    postalCodeLabel: "📍 Kodi postar",
    postalCodePlaceholder: "10115",
    uploadPhotoLabel: "📸 Ngarko Fotografinë",
    uploadPhoto: "Ngarko Fotografinë",
    uploadPhotoDescription: "Kliko këtu ose zvarrit një fotografi të mbeturinave tuaja këtu",
    analyzeButton: "🔍 Analizo Mbeturinat e Mia",
    analyzing: "Duke analizuar...",
    validPostalCode: "Kod postar i vlefshëm",
    invalidPostalCode: "⚠️ Ju lutemi vendosni një kod postar gjerman të vlefshëm me 5 shifra",
    whyImportant: "Pse është e rëndësishme ndarja e duhur e mbeturinave?",
    reason1: "Mbrojtja e mjedisit përmes riciklimit dhe ripërdorimit",
    reason2: "Reduktimi i mbeturinave të groposjes dhe emetimeve të CO2",
    reason3: "Përputhja me ligjet mjedisore gjermane",
    reason4: "Kursimi i kostove në heqjen e mbeturinave",
    languageSelector: "Zgjidh Gjuhën",
    analysisComplete: "Analiza u Përfundua",
    analysisCompleteDescription: "Këtu janë udhëzimet tuaja të ndarjes",
    analysisError: "Analiza Dështoi",
    analysisErrorDescription: "Ndodhi një gabim gjatë analizës",
    newAnalysis: "Fillo Analizë të Re",
    genericError: "Ndodhi një gabim i papritur. Ju lutemi provoni përsëri.",
    detectLocation: "Zbulo Vendndodhjen",
    geolocationNotSupported: "Gjeolokalizimi nuk mbështetet nga ky shfletues",
    locationPermissionDenied: "Qasja në vendndodhje u refuzua",
    locationUnavailable: "Vendndodhja nuk është e disponueshme",
    locationTimeout: "Koha e zbulimit të vendndodhjes mbaroi",
    locationError: "Gabim në zbulimin e vendndodhjes",
    geocodingError: "Gabim në përcaktimin e kodit postar",
    noGermanPostalCodeFound: "Nuk u gjet kod postar gjerman për këtë vendndodhje",
    apiKeyRestrictionError: "Gabim kufizimi i çelësit API. Ju lutemi kontaktoni administratorin."
  },
  da: {
    title: "Affaldssortering Assistent",
    subtitle: "Korrekt Affaldssortering i Tyskland",
    description: "Indtast dit postnummer og upload et billede af dit affald. Vi hjælper dig med at sortere det korrekt.",
    postalCodeLabel: "📍 Postnummer",
    postalCodePlaceholder: "10115",
    uploadPhotoLabel: "📸 Upload Billede",
    uploadPhoto: "Upload Billede",
    uploadPhotoDescription: "Klik her eller træk et billede af dit affald herhen",
    analyzeButton: "🔍 Analyser Mit Affald",
    analyzing: "Analyserer...",
    validPostalCode: "Gyldigt postnummer",
    invalidPostalCode: "⚠️ Indtast venligst et gyldigt 5-cifret tysk postnummer",
    whyImportant: "Hvorfor er korrekt affaldssortering vigtig?",
    reason1: "Miljøbeskyttelse gennem genbrug og genanvendelse",
    reason2: "Reduktion af lossepladsaffald og CO2-udledning",
    reason3: "Overholdelse af tyske miljølove",
    reason4: "Omkostningsbesparelser ved affaldsbortskaffelse",
    languageSelector: "Vælg Sprog",
    analysisComplete: "Analyse Fuldført",
    analysisCompleteDescription: "Her er dine sorteringsinstruktioner",
    analysisError: "Analyse Mislykkedes",
    analysisErrorDescription: "Der opstod en fejl under analysen",
    newAnalysis: "Start Ny Analyse",
    genericError: "Der opstod en uventet fejl. Prøv venligst igen.",
    detectLocation: "Registrer Placering",
    geolocationNotSupported: "Geolokalisering understøttes ikke af denne browser",
    locationPermissionDenied: "Adgang til placering blev nægtet",
    locationUnavailable: "Placering er ikke tilgængelig",
    locationTimeout: "Timeout for placeringsregistrering",
    locationError: "Fejl ved registrering af placering",
    geocodingError: "Fejl ved bestemmelse af postnummer",
    noGermanPostalCodeFound: "Intet tysk postnummer fundet for denne placering",
    apiKeyRestrictionError: "API-nøgle begrænsningsfejl. Kontakt venligst administratoren."
  },
  uk: {
    title: "Помічник з Сортування Сміття",
    subtitle: "Правильне Сортування Відходів у Німеччині",
    description: "Введіть ваш поштовий індекс та завантажте фото вашого сміття. Ми допоможемо правильно його відсортувати.",
    postalCodeLabel: "📍 Поштовий індекс",
    postalCodePlaceholder: "10115",
    uploadPhotoLabel: "📸 Завантажити Фото",
    uploadPhoto: "Завантажити Фото",
    uploadPhotoDescription: "Натисніть тут або перетягніть фото вашого сміття сюди",
    analyzeButton: "🔍 Проаналізувати Моє Сміття",
    analyzing: "Аналізуємо...",
    validPostalCode: "Дійсний поштовий індекс",
    invalidPostalCode: "⚠️ Будь ласка, введіть дійсний 5-значний німецький поштовий індекс",
    whyImportant: "Чому важливе правильне сортування сміття?",
    reason1: "Захист довкілля через переробку та повторне використання",
    reason2: "Зменшення кількості сміттєзвалищ та викидів CO2",
    reason3: "Дотримання німецького екологічного законодавства",
    reason4: "Економія коштів на утилізації відходів",
    languageSelector: "Оберіть Мову",
    analysisComplete: "Аналіз Завершено",
    analysisCompleteDescription: "Ось ваші інструкції з сортування",
    analysisError: "Помилка Аналізу",
    analysisErrorDescription: "Сталася помилка під час аналізу",
    newAnalysis: "Почати Новий Аналіз",
    genericError: "Сталася неочікувана помилка. Будь ласка, спробуйте знову.",
    detectLocation: "Визначити Місцезнаходження",
    geolocationNotSupported: "Геолокація не підтримується цим браузером",
    locationPermissionDenied: "Доступ до місцезнаходження було відхилено",
    locationUnavailable: "Місцезнаходження недоступне",
    locationTimeout: "Час визначення місцезнаходження вичерпано",
    locationError: "Помилка визначення місцезнаходження",
    geocodingError: "Помилка визначення поштового індексу",
    noGermanPostalCodeFound: "Німецький поштовий індекс для цього місцезнаходження не знайдено",
    apiKeyRestrictionError: "Помилка обмеження API ключа. Будь ласка, зверніться до адміністратора."
  }
};